// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestSystem.Infrastructure.Data;

#nullable disable

namespace TestSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260102170553_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestSystem.Core.Entity.ClassRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_class_rooms");

                    b.ToTable("class_rooms", (string)null);
                });

            modelBuilder.Entity("TestSystem.Core.Entity.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id", "UserId", "TaskId")
                        .HasName("pk_packages");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_packages_task_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_packages_user_id");

                    b.ToTable("packages", (string)null);
                });

            modelBuilder.Entity("TestSystem.Core.Entity.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClassRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_room_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("InputSample")
                        .HasColumnType("text")
                        .HasColumnName("input_sample");

                    b.Property<string>("OutputSample")
                        .HasColumnType("text")
                        .HasColumnName("output_sample");

                    b.Property<string>("Tests")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tests");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tasks");

                    b.HasIndex("ClassRoomId")
                        .HasDatabaseName("ix_tasks_class_room_id");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("TestSystem.Core.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_password");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TestSystem.Core.Entity.UserClassRoom", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ClassRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_room_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("UserId", "ClassRoomId")
                        .HasName("pk_user_class_rooms");

                    b.HasIndex("ClassRoomId")
                        .HasDatabaseName("ix_user_class_rooms_class_room_id");

                    b.ToTable("user_class_rooms", (string)null);
                });

            modelBuilder.Entity("TestSystem.Core.Entity.Package", b =>
                {
                    b.HasOne("TestSystem.Core.Entity.TaskEntity", "Task")
                        .WithMany("Packages")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_packages_tasks_task_id");

                    b.HasOne("TestSystem.Core.Entity.User", "User")
                        .WithMany("Packages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_packages_users_user_id");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestSystem.Core.Entity.TaskEntity", b =>
                {
                    b.HasOne("TestSystem.Core.Entity.ClassRoom", "ClassRoom")
                        .WithMany("Tasks")
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_class_rooms_class_room_id");

                    b.Navigation("ClassRoom");
                });

            modelBuilder.Entity("TestSystem.Core.Entity.UserClassRoom", b =>
                {
                    b.HasOne("TestSystem.Core.Entity.ClassRoom", "ClassRoom")
                        .WithMany("UserClassRooms")
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_class_rooms_class_rooms_class_room_id");

                    b.HasOne("TestSystem.Core.Entity.User", "User")
                        .WithMany("UserClassRooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_class_rooms_users_user_id");

                    b.Navigation("ClassRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestSystem.Core.Entity.ClassRoom", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("UserClassRooms");
                });

            modelBuilder.Entity("TestSystem.Core.Entity.TaskEntity", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("TestSystem.Core.Entity.User", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("UserClassRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
